### ISSUE TITLE
device tree loading and spi bus

### ISSUE THREAD

**Issue by fredoche** [spartacus06/rpi2-fedora-image-builder#2]
Hi,
I'm trying to use the spi bus to connect a led screen. However, there is no mention of /dev/spidev0.0 in the filesystem. 
I'm not very litterate in kernel config, so I may certainly be missing something, but do you know if that bus is supposed to appear, or should I start the kernel with a specific option to load the 'dtb' and hence have access to the bus? 

Thank you for your input.

**Comment by fredoche** [comment]
I found this on my quest of information, might be related ... http://www.raspberrypi.org/documentation/configuration/device-tree.md

**Comment by fredoche** [comment]
ok so i created a /boot/config.txt file
[root@localhost ~]# cat /boot/config.txt 

```
# Uncomment some or all of these to enable the optional hardware interfaces
#dtparam=i2c_arm=on
#dtparam=i2s=on
dtparam=spi=on
```

and I got the spi bus detectable on /dev/spidev0

**Comment by sjenning** [comment]
sorry, for not replying to this.  i just pushed some new features that allows users to include a config.txt in the built image.  hopefully that will be useful in preserving custom config.txt needs such as yours.

since it seems that this is a configuration issue, not an issue with the image builder, and you have it solved, i'm going to close.
