### ISSUE TITLE
Local Image

### ISSUE THREAD

**Issue by nolteg** [spartacus06/rpi2-fedora-image-builder#4]
Hi Seth, is there a possible to create a local directory to store images in the "settings.conf" which should be used during the installation before the "IMAGEURL=" is used to download the image?

**Comment by sjenning** [comment]
There is code in mkimage.sh to check for the image file in the base directory before trying to download it.  Since the images are large, you don't want to download the same image each time.  Unless you remove the image file (*.raw.xz), it should reuse the same downloaded image.

Is this what you are asking about?

**Comment by nolteg** [comment]
Ok, great. That's exactly what I was looking for. Thank you.

**Comment by nolteg** [comment]
Apologies, one more question. When the images are created I noticed there are no partitions created for swap space like in conventional images. Is it ok to leave this out?

**Comment by sjenning** [comment]
Yes, SD cards have very low IOPS and don't have good wear leveling so I decided not to make a swap partition.  It would be slow and, if heavily used, will burn out your card.  However I wouldn't be against a non-default option to create one.

**Comment by nolteg** [comment]
interesting. Thanks.
